# Generated by Django 5.0.6 on 2024-07-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(choices=[('Monofásico', 'Monofásico'), ('Bifásico', 'Bifásico'), ('Trifásico', 'Trifásico')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=9)),
                ('prefixo_local', models.CharField(choices=[('Rua', 'Rua'), ('Av.', 'Avenida'), ('Pov.', 'Povoado'), ('Est.', 'Estrada')], max_length=4)),
                ('rua', models.CharField(max_length=200)),
                ('num_logradouro', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('seforrural', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='TipoUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTipo', models.CharField(choices=[('Usina', 'Usina'), ('Compensadora', 'Compensadora')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_UC', models.CharField(max_length=12)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempoPosse', models.IntegerField(blank=True, null=True)),
                ('tensaoNominal', models.CharField(choices=[('127/220', '127/220'), ('220/380', '220/380')], max_length=10)),
                ('resideoucomercial', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial')], max_length=11)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='clientes.cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.endereco')),
                ('tipoUC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.tipouc')),
            ],
            options={
                'ordering': ('tipoUC',),
            },
        ),
    ]
