# Generated by Django 5.0.6 on 2024-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uc',
            name='tempoPosse',
            field=models.IntegerField(default=0),
        ),
    ]
