# Generated by Django 5.0.6 on 2024-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0002_alter_endereco_complemento_alter_uc_tempoposse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default='', max_length=200),
        ),
    ]
