# Generated by Django 5.0.6 on 2024-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0005_modulosolar_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulosolar',
            name='potencia',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='producaoMedia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
