# Generated by Django 5.0.6 on 2024-07-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0003_alter_endereco_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='complemento',
        ),
    ]
