# Generated by Django 5.0.6 on 2024-07-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0004_remove_endereco_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('area', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('garantiaAno', models.IntegerField()),
                ('codInmetro', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoTotal', models.IntegerField()),
                ('qtdeModulos', models.IntegerField()),
                ('producaoMedia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtdeInv', models.IntegerField()),
                ('valorProposta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.modulosolar')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.uc')),
            ],
        ),
    ]
